creation_rules:
    - path_regex: .*configs-to-encrypt/.*
      kms: arn:aws:kms:eu-central-1:640753244498:key/d8362fe3-d807-42de-a214-f6a1034a6da1
      aws_profile: MFA
      age: age1jsfcat6jfxv3r3n5dvd3ukka9ahalyv7zzu2hx63jpfgwdqj2exswfsnhy

