server:
    port: ENC[AES256_GCM,data:KVf4KA==,iv:zFXs1P/ZWzQ8VeBq8tOpLhcuok4zcafhn7ODJriO5nU=,tag:LmHuNMQV69J2pqhGA9U0vw==,type:int]
db:
    type: ENC[AES256_GCM,data:pmHsacsRbQ==,iv:VWVsrsMufSTTNOt/vQdXxWIoY6ZgWzeRzBqOQjWuw9g=,tag:NLPfm8at5IlU6yKq3cvytA==,type:str]
    username: ENC[AES256_GCM,data:Ed1ow+Tc00IsxN0=,iv:ktSnKwqjo+Ritequ17yEPI5Fdt29kaxF9KRh/fni+00=,tag:qEaqzWjv3SBJkJX5rcu3pw==,type:str]
    password: ENC[AES256_GCM,data:3Zbo+zWLhp9IPBUPXbOWpQ==,iv:2WzJ0+/+AENCKdgqGqZ/MC10KHtutGhhZqqD6gBMn98=,tag:aRXcdDljOpngw5N35mrMtg==,type:str]
    synchronize: ENC[AES256_GCM,data:vaMqZg==,iv:+vxzWoQU5UGzvYFE99JUJyjNkXHJUzp+xKfH8gcA3kg=,tag:XiR4xOrcJ1ExNbWhhgcOcg==,type:bool]
jwt:
    expiresIn: ENC[AES256_GCM,data:E5ydtw==,iv:wOeeUNOSsybl5kU7RRX8imRUumDvsBN5NbeMDcI0zEs=,tag:L/c6KdEtwZ34C7PDUgVq8Q==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:640753244498:key/d8362fe3-d807-42de-a214-f6a1034a6da1
          created_at: "2022-01-26T10:55:04Z"
          enc: AQICAHgwQKJMmvInkuMXExzSSHtUc3clvoog02yhboeEhEBaQQEc2l21IpZhIdFL5qKO60jZAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMAeCp3kkYTFg7tAQoAgEQgDtUpFqQnYsqY2TwmnjcYzyi/HHuw1UE+5CJ2TgeNgSfrpda2q4uTFPrB3h35ByYqnBgzSSq+fD77cIoNw==
          aws_profile: MFA
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jsfcat6jfxv3r3n5dvd3ukka9ahalyv7zzu2hx63jpfgwdqj2exswfsnhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Vy8rTWJJclRqSkdyWEZN
            WVlmcjZ5ZytEeXhmTDY0a3R6am1qbWlwK3lnCnFSckZiU2JKdTRzOHBWSmVNMnpl
            QmJKa21ERFE0WFZaNVZuaDBSRWs0RXMKLS0tIFdtMXZrOHlFYVc3b01JTXJEZUtM
            Nkg3VnM4eHBCWW55WTA5ZklyTGs4TVUKLbFRJKN/O0PQGgQcBxYC8+UxhLQlTmHC
            2m2Pf24UcSq7YREY7jhAcFTA4QTyWxDp62tQX9KUcGT5k3FIky98DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-26T10:55:04Z"
    mac: ENC[AES256_GCM,data:9FDOhbnzvZBQhmDCKyZ9OrXfNiRgPt08gB6eSGiBrb1CSg97p1MXxomVacAEAiL0hwx4T+9yFB2H4/bu9xEzXNnFczDmuN23EvgOlmUHGBDR/Tnlp3tjUMceN/arUKycGkELAmpfOjEWeVS7EnIJooOEGz0ZfYbo6+z2MuWS0/U=,iv:mjbp2cKK92lp3YmSI1e/xQU7gSreIHDgHOa6bpEGFuM=,tag:G330NfFuBcSmZHmMgMhxig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
